# Generated by Django 4.2.3 on 2023-11-21 09:07

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Property Title"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        unique=True,
                        verbose_name="Property Reference Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Update this field",
                        help_text="Describe the property.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="GH", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Accra", max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "digital_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Digital Address"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Property Price",
                    ),
                ),
                (
                    "property_dimensions",
                    models.TextField(
                        help_text="Provide the dimensions of the property.",
                        verbose_name="Property Size",
                    ),
                ),
                (
                    "advert_type",
                    models.CharField(
                        choices=[
                            ("For Sale", "For Sale"),
                            ("For Rent", "For Rent"),
                            ("Auction", "Auction"),
                        ],
                        default="For Rent",
                        max_length=20,
                        verbose_name="Advert Type",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Apartment", "Apartment"),
                            ("Office", "Office"),
                            ("Warehouse", "Warehouse"),
                            ("Studio", "Studio"),
                            ("Store", "Store"),
                            ("Other", "Other"),
                        ],
                        default="Apartment",
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        default="/property.jpeg",
                        null=True,
                        upload_to="",
                        verbose_name="Primary Picture",
                    ),
                ),
                (
                    "secondary_image1",
                    models.ImageField(
                        blank=True,
                        default="/property.jpeg",
                        null=True,
                        upload_to="",
                        verbose_name="Secondary Picture 1",
                    ),
                ),
                (
                    "secondary_image2",
                    models.ImageField(
                        blank=True,
                        default="/property.jpeg",
                        null=True,
                        upload_to="",
                        verbose_name="Secondary Picture 2",
                    ),
                ),
                (
                    "secondary_image3",
                    models.ImageField(
                        blank=True,
                        default="/property.jpeg",
                        null=True,
                        upload_to="",
                        verbose_name="Secondary Picture 3",
                    ),
                ),
                (
                    "secondary_image4",
                    models.ImageField(
                        blank=True,
                        default="/property.jpeg",
                        null=True,
                        upload_to="",
                        verbose_name="Secondary Picture 4",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published status"),
                ),
                (
                    "views",
                    models.IntegerField(default=0, verbose_name="Total Property Views"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="property_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent, Seller or Buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PropertyViews",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ip", models.CharField(max_length=300, verbose_name="IP Address")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_views",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property View",
                "verbose_name_plural": "Property Views",
            },
        ),
    ]
